image:
  file: .gitpod.Dockerfile
tasks:
  - init: echo "Replace me with a build script for the project."
    command: mkdir -p /workspace/data && mongod --port 27019 --dbpath /workspace/data && cd src/main/resources && mongoimport --type csv -d patient -c patient --headerline maindata.csv &
  - init: echo "Setting Up Kafka and Zookeeper"
    command: sh build.sh
